
import {
  LayoutGrid, Laptop, Smartphone, Watch, Headphones, Camera,
  Shirt, Coffee, Pizza, Briefcase, Gift, Utensils, Package,
  ShoppingBag, Music, Zap, Wrench, Smile, Monitor,
  Apple, Cake, Wine, Beer, CupSoda, IceCream, Fish, Beef, Carrot, Croissant, Egg, ChefHat,
  Car, Home, Book, Pen, Scissors, Dumbbell, Bike, Gamepad, Tv, Speaker, Mic, Video, Film, Ticket, Tag, ShoppingCart, CreditCard, Wallet, Store, Building,
  Activity, Heart, Star, Sun, Moon, Cloud, Flame, Droplet, Leaf, Flower, Snowflake
} from 'lucide-react';

// Centralized icon map for categories
export const iconMap: Record<string, any> = {
  'grid': LayoutGrid,
  'laptop': Laptop,
  'smartphone': Smartphone,
  'watch': Watch,
  'headphones': Headphones,
  'camera': Camera,
  'monitor': Monitor,
  'shirt': Shirt,
  'coffee': Coffee,
  'pizza': Pizza,
  'utensils': Utensils,
  'package': Package,
  'briefcase': Briefcase,
  'gift': Gift,
  'bag': ShoppingBag,
  'music': Music,
  'zap': Zap,
  'tool': Wrench,
  'smile': Smile,
  'apple': Apple,
  'cake': Cake,
  'wine': Wine,
  'beer': Beer,
  'soda': CupSoda,
  'icecream': IceCream,
  'fish': Fish,
  'beef': Beef,
  'carrot': Carrot,
  'croissant': Croissant,
  'egg': Egg,
  'chef': ChefHat,
  'car': Car,
  'home': Home,
  'book': Book,
  'pen': Pen,
  'scissors': Scissors,
  'dumbbell': Dumbbell,
  'bike': Bike,
  'gamepad': Gamepad,
  'tv': Tv,
  'speaker': Speaker,
  'mic': Mic,
  'video': Video,
  'film': Film,
  'ticket': Ticket,
  'tag': Tag,
  'cart': ShoppingCart,
  'card': CreditCard,
  'wallet': Wallet,
  'store': Store,
  'building': Building,
  'activity': Activity,
  'heart': Heart,
  'star': Star,
  'sun': Sun,
  'moon': Moon,
  'cloud': Cloud,
  'flame': Flame,
  'droplet': Droplet,
  'leaf': Leaf,
  'flower': Flower,
  'snowflake': Snowflake
};
