def _create_indexes(cursor):
    indexes = [
        "CREATE INDEX IF NOT EXISTS idx_invoices_created ON invoices(created_at)",
        "CREATE INDEX IF NOT EXISTS idx_invoices_void ON invoices(is_void)",
        "CREATE INDEX IF NOT EXISTS idx_invoices_customer ON invoices(customer_id)",
        "CREATE INDEX IF NOT EXISTS idx_invoices_branch ON invoices(branch_id, created_at)",
        "CREATE INDEX IF NOT EXISTS idx_invoices_order_type ON invoices(order_type)",
        "CREATE INDEX IF NOT EXISTS idx_invoices_fulfillment ON invoices(fulfillment_status)",
        "CREATE INDEX IF NOT EXISTS idx_invoice_items_inv ON invoice_items(invoice_id)",
        "CREATE INDEX IF NOT EXISTS idx_invoice_items_prod ON invoice_items(product_id)",
        "CREATE INDEX IF NOT EXISTS idx_products_sku ON products(sku)",
        "CREATE INDEX IF NOT EXISTS idx_products_barcode ON products(barcode)",
        "CREATE INDEX IF NOT EXISTS idx_products_category ON products(category)",
        "CREATE INDEX IF NOT EXISTS idx_products_type ON products(type)",
        "CREATE INDEX IF NOT EXISTS idx_customers_code ON customers(code)",
        "CREATE INDEX IF NOT EXISTS idx_customers_phone ON customers(phone)",
        "CREATE INDEX IF NOT EXISTS idx_suppliers_code ON suppliers(code)",
        "CREATE INDEX IF NOT EXISTS idx_sessions_login ON cashier_sessions(login_at)",
        "CREATE INDEX IF NOT EXISTS idx_sessions_branch ON cashier_sessions(branch_id)",
        "CREATE INDEX IF NOT EXISTS idx_returns_inv ON returns(original_invoice_id)",
        "CREATE INDEX IF NOT EXISTS idx_returns_date ON returns(created_at)",
        "CREATE INDEX IF NOT EXISTS idx_return_items_ret ON return_items(return_id)",
        "CREATE INDEX IF NOT EXISTS idx_stock_mov_prod ON stock_movements(product_id)",
        "CREATE INDEX IF NOT EXISTS idx_stock_mov_date ON stock_movements(created_at)",
        "CREATE INDEX IF NOT EXISTS idx_z_reports_branch ON z_reports(branch_id)",
        "CREATE INDEX IF NOT EXISTS idx_ops_log_created ON ops_log(created_at)",
        "CREATE INDEX IF NOT EXISTS idx_ops_log_branch ON ops_log(branch_id, created_at)",
        # New indexes
        "CREATE INDEX IF NOT EXISTS idx_quotations_date ON quotations(date)",
        "CREATE INDEX IF NOT EXISTS idx_quotations_status ON quotations(status)",
        "CREATE INDEX IF NOT EXISTS idx_quotations_customer ON quotations(customer_id)",
        "CREATE INDEX IF NOT EXISTS idx_expenses_date ON expenses(date)",
        "CREATE INDEX IF NOT EXISTS idx_expenses_category ON expenses(category)",
        "CREATE INDEX IF NOT EXISTS idx_purchases_date ON purchases(date)",
        "CREATE INDEX IF NOT EXISTS idx_purchases_supplier ON purchases(supplier_id)",
        "CREATE INDEX IF NOT EXISTS idx_stock_adj_product ON stock_adjustments(product_id)",
        "CREATE INDEX IF NOT EXISTS idx_stock_adj_date ON stock_adjustments(date)",
        "CREATE INDEX IF NOT EXISTS idx_shifts_status ON shifts(status)",
        "CREATE INDEX IF NOT EXISTS idx_shifts_start ON shifts(start_time)",
        "CREATE INDEX IF NOT EXISTS idx_customer_payments_cust ON customer_payments(customer_id)",
        "CREATE INDEX IF NOT EXISTS idx_customer_payments_date ON customer_payments(date)",
        "CREATE INDEX IF NOT EXISTS idx_inventory_items_wh ON inventory_items(warehouse_id)",
        "CREATE INDEX IF NOT EXISTS idx_inventory_items_prod ON inventory_items(product_id)",
        "CREATE INDEX IF NOT EXISTS idx_batches_product ON product_batches(product_id)",
        "CREATE INDEX IF NOT EXISTS idx_batches_expiry ON product_batches(expiry_date)",
        "CREATE INDEX IF NOT EXISTS idx_serials_product ON product_serials(product_id)",
        "CREATE INDEX IF NOT EXISTS idx_serials_serial ON product_serials(serial_number)",
        "CREATE INDEX IF NOT EXISTS idx_serials_status ON product_serials(status)",
        "CREATE INDEX IF NOT EXISTS idx_tables_status ON dining_tables(status)",
        "CREATE INDEX IF NOT EXISTS idx_loyalty_customer ON loyalty_transactions(customer_id)",
        "CREATE INDEX IF NOT EXISTS idx_loyalty_date ON loyalty_transactions(date)",
        "CREATE INDEX IF NOT EXISTS idx_promotions_active ON promotions(is_active)",
        "CREATE INDEX IF NOT EXISTS idx_promotions_code ON promotions(code)",
        "CREATE INDEX IF NOT EXISTS idx_installment_plans_cust ON installment_plans(customer_id)",
        "CREATE INDEX IF NOT EXISTS idx_installment_plans_status ON installment_plans(status)",
        "CREATE INDEX IF NOT EXISTS idx_installment_pay_plan ON installment_payments(plan_id)",
        "CREATE INDEX IF NOT EXISTS idx_installment_pay_due ON installment_payments(due_date)",
        "CREATE INDEX IF NOT EXISTS idx_rentals_customer ON rentals(customer_id)",
        "CREATE INDEX IF NOT EXISTS idx_rentals_status ON rentals(status)",
        "CREATE INDEX IF NOT EXISTS idx_rentals_dates ON rentals(pickup_date, return_date)",
        "CREATE INDEX IF NOT EXISTS idx_studio_bookings_date ON studio_bookings(date)",
        "CREATE INDEX IF NOT EXISTS idx_studio_bookings_camera ON studio_bookings(camera_id)",
        "CREATE INDEX IF NOT EXISTS idx_accounts_code ON accounts(code)",
        "CREATE INDEX IF NOT EXISTS idx_accounts_type ON accounts(type)",
        "CREATE INDEX IF NOT EXISTS idx_journal_entries_date ON journal_entries(date)",
        "CREATE INDEX IF NOT EXISTS idx_journal_lines_entry ON journal_entry_lines(entry_id)",
        "CREATE INDEX IF NOT EXISTS idx_journal_lines_account ON journal_entry_lines(account_id)",
        "CREATE INDEX IF NOT EXISTS idx_checks_due ON bank_checks(due_date)",
        "CREATE INDEX IF NOT EXISTS idx_checks_status ON bank_checks(status)",
        "CREATE INDEX IF NOT EXISTS idx_checks_type ON bank_checks(type)",
        "CREATE INDEX IF NOT EXISTS idx_assets_category ON fixed_assets(category)",
        "CREATE INDEX IF NOT EXISTS idx_fiscal_years_status ON fiscal_years(status)",
        "CREATE INDEX IF NOT EXISTS idx_reconciliations_account ON bank_reconciliations(account_id)",
        # Phase 2: Payroll, Logs, Labels
        "CREATE INDEX IF NOT EXISTS idx_payroll_user ON payroll_records(user_id)",
        "CREATE INDEX IF NOT EXISTS idx_payroll_month ON payroll_records(month)",
        "CREATE INDEX IF NOT EXISTS idx_payroll_user_month ON payroll_records(user_id, month)",
        "CREATE INDEX IF NOT EXISTS idx_activity_logs_date ON activity_logs(date)",
        "CREATE INDEX IF NOT EXISTS idx_activity_logs_type ON activity_logs(type)",
        "CREATE INDEX IF NOT EXISTS idx_activity_logs_status ON activity_logs(status)",
        "CREATE INDEX IF NOT EXISTS idx_activity_logs_user ON activity_logs(user_name)",
        "CREATE INDEX IF NOT EXISTS idx_label_templates_type ON label_templates(type)",
        # Phase 3: Attendance, InventoryCount, BranchTransfers, Maintenance, Recipes, Delivery, PurchaseOrders
        "CREATE INDEX IF NOT EXISTS idx_attendance_user ON attendance_records(user_id)",
        "CREATE INDEX IF NOT EXISTS idx_attendance_date ON attendance_records(date)",
        "CREATE INDEX IF NOT EXISTS idx_attendance_user_date ON attendance_records(user_id, date)",
        "CREATE INDEX IF NOT EXISTS idx_inv_counts_status ON inventory_counts(status)",
        "CREATE INDEX IF NOT EXISTS idx_inv_counts_wh ON inventory_counts(warehouse_id)",
        "CREATE INDEX IF NOT EXISTS idx_inv_count_items_count ON inventory_count_items(count_id)",
        "CREATE INDEX IF NOT EXISTS idx_inv_count_items_prod ON inventory_count_items(product_id)",
        "CREATE INDEX IF NOT EXISTS idx_transfers_status ON branch_transfers(status)",
        "CREATE INDEX IF NOT EXISTS idx_transfers_from ON branch_transfers(from_warehouse_id)",
        "CREATE INDEX IF NOT EXISTS idx_transfers_to ON branch_transfers(to_warehouse_id)",
        "CREATE INDEX IF NOT EXISTS idx_transfer_items_tid ON branch_transfer_items(transfer_id)",
        "CREATE INDEX IF NOT EXISTS idx_maintenance_status ON maintenance_orders(status)",
        "CREATE INDEX IF NOT EXISTS idx_maintenance_customer ON maintenance_orders(customer_name)",
        "CREATE INDEX IF NOT EXISTS idx_recipes_product ON recipes(product_id)",
        "CREATE INDEX IF NOT EXISTS idx_recipe_items_recipe ON recipe_items(recipe_id)",
        "CREATE INDEX IF NOT EXISTS idx_recipe_items_ingredient ON recipe_items(ingredient_id)",
        "CREATE INDEX IF NOT EXISTS idx_delivery_status ON delivery_assignments(status)",
        "CREATE INDEX IF NOT EXISTS idx_delivery_driver ON delivery_assignments(driver_id)",
        "CREATE INDEX IF NOT EXISTS idx_delivery_invoice ON delivery_assignments(invoice_id)",
        "CREATE INDEX IF NOT EXISTS idx_po_status ON purchase_orders(status)",
        "CREATE INDEX IF NOT EXISTS idx_po_supplier ON purchase_orders(supplier_id)",
        "CREATE INDEX IF NOT EXISTS idx_po_items_po ON purchase_order_items(po_id)",
        # v1.35 Expansion Indexes
        "CREATE INDEX IF NOT EXISTS idx_tables_branch ON table_resources(branch_id)",
        "CREATE INDEX IF NOT EXISTS idx_reservations_table ON table_reservations(table_id)",
        "CREATE INDEX IF NOT EXISTS idx_reservations_start ON table_reservations(start_at)",
        "CREATE INDEX IF NOT EXISTS idx_kds_status ON kitchen_tickets(status)",
        "CREATE INDEX IF NOT EXISTS idx_rentals_product ON rental_bookings(product_id)",
        "CREATE INDEX IF NOT EXISTS idx_rentals_due ON rental_bookings(due_at)",
        "CREATE INDEX IF NOT EXISTS idx_online_orders_status ON online_orders(status)",
        "CREATE INDEX IF NOT EXISTS idx_online_orders_channel ON online_orders(channel_id)",
        "CREATE INDEX IF NOT EXISTS idx_webhooks_dedupe ON webhook_events(dedupe_key)",
        "CREATE INDEX IF NOT EXISTS idx_notifications_recipient ON notifications(recipient)",
        "CREATE INDEX IF NOT EXISTS idx_notifications_status ON notifications(status)",
        "CREATE INDEX IF NOT EXISTS idx_recipe_logs_recipe ON recipe_production_logs(recipe_id)",
    ]
    for sql in indexes:
        cursor.execute(sql)
