import { 
  LayoutDashboard, ShoppingCart, Package, History, Store, Users, Settings, 
  PieChart, Wallet, Truck, ClipboardList, ClipboardX, 
  LockKeyhole, ShieldCheck, QrCode, LogOut, Bell, Sparkles,
  AlertTriangle, Calendar, Info, ListChecks, ScanLine, FileText, Landmark, LayoutGrid, ChefHat, Layers, FileClock, BookOpen, ScrollText, BarChart4,
  Banknote, Calculator, Video, Printer, Activity, Zap, Gem, Building2, Power, Shirt,
  Star, Percent, UserMinus, Brain, CalendarClock, RotateCcw, ArrowLeftRight, ClipboardCheck, CircleUser, Clock, Utensils, Wrench, Building, Target, WalletCards, Globe, Gift, Repeat,
  ChevronDown, ChevronRight, Sun, Moon, FileSearch, Briefcase, ListTodo, Ticket, Navigation, FileSignature, FileBarChart, Filter, LifeBuoy, Megaphone, Ship, Scale, Folder, Factory, ShieldAlert, UserCheck, DatabaseBackup, HeartHandshake, AlertOctagon, UserPlus, MessageSquare, Receipt, Coins, Laptop, TrendingUp, CalendarDays, MonitorSmartphone, LineChart, RefreshCw,
  Search, X, Trash2, Gavel, FolderOpen, Award, Scissors, Edit3, FileEdit, Network, FileCheck, Box, CalendarX, TrendingDown, PenTool, Key, MapPin, Server, Bookmark, Headset, Coffee, DollarSign, ShoppingBag, Warehouse, MessageCircle, FileCode2, Salad, Camera, Route, Bus, Smartphone
} from 'lucide-react';

export const pageKeyFeatures: Record<string, string[]> = {
    '/': ['لوحة القيادة', 'ملخص المبيعات', 'الإيرادات', 'تحليلات الأداء'],
    '/pos': ['بيع مباشر', 'كاشير', 'فاتورة جديدة', 'تعليق وحفظ الفواتير', 'جرد سريع'],
    '/restaurant-pos': ['بيع مطعم', 'طلبات طاولات', 'تيك أواي', 'توصيل دليفري', 'دمج طاولات'],
    '/waiter': ['النادل', 'كابتن صالة', 'طلبات', 'تقديم', 'أجهزة لوحية', 'طلب فاتورة'],
    '/kitchen': ['شاشة المطبخ', 'متابعة الطلبات', 'تجهيز الوجبات', 'حالة الطبخ'],
    '/tables': ['إدارة الطاولات', 'الصالة الرئيسة', 'المناطق', 'حالة الطاولة'],
    '/rentals': ['حجز فساتين', 'بدلات', 'إعارة', 'تأمين مرتجع', 'مواعيد الاستلام'],
    '/tailoring': ['طلبات التفصيل', 'خياطة', 'تفصيل ثياب', 'البروفة', 'ترزي', 'ملابس'],
    '/studio': ['حجز جلسات تصوير', 'استوديو', 'ألبومات', 'مواعيد فوتوجرافر'],
    '/delivery': ['متابعة المناديب', 'توصيل الطلبات', 'حالة التوصيل', 'تخصيص السائقين'],
    '/call-center': ['كول سنتر', 'استلام طلبات الدليفري', 'تسجيل طلبات الهاتف', 'خدمة العملاء'],
    '/employee-portal': ['بوابة الموظف', 'سجل الحضور', 'طلب إجازة', 'كشف الراتب', 'بصمة'],
    '/orders': ['سجل الفواتير', 'أرشيف المبيعات', 'طباعة فاتورة', 'مراجعة المبيعات'],
    '/quotations': ['إنشاء عرض سعر', 'تسعيرة للعميل', 'تحويل العرض لفاتورة', 'عروض الشركات'],
    '/b2b-sales': ['مبيعات الجملة', 'فواتير الشركات', 'اعتمادات', 'شروط الدفع'],
    '/ecommerce': ['طلبات المتجر الإلكتروني', 'مبيعات الأونلاين', 'ربط المتجر'],
    '/layaways': ['نظام العربون', 'حجز بضاعة', 'تسديدات وعربون', 'استلام مؤجل'],
    '/commodity-contracts': ['عقود آجلة', 'حجز بضاعة', 'سحب البضاعة', 'تغطية عجز الطوارئ', 'سجلات التسليم', 'استرداد حجز'],
    '/van-sales': ['مبيعات التوزيع', 'مناديب المبيعات', 'خطوط السير', 'سيارات التوزيع'],
    '/returns': ['مرتجعات البيع', 'إرجاع بضاعة', 'استرداد أموال', 'تالف'],
    '/fulfillment': ['تجهيز الطلبات', 'تعبئة وتغليف', 'شحن الطلبات', 'Pick & Pack'],
    '/sales-targets': ['أهداف المبيعات', 'تارجت المناديب', 'العمولات', 'أداء الفريق'],
    '/customers': ['إدارة العملاء', 'حسابات العملاء', 'كشف حساب', 'مديونيات العملاء'],
    '/loyalty': ['نقاط الولاء', 'استبدال النقاط', 'عملاء مميزون', 'مكافآت'],
    '/promotions': ['عروض وتخفيضات', 'خصومات', 'كوبونات', 'بروموكود'],
    '/gift-cards': ['بطاقات هدايا', 'رصيد مجاني', 'قسائم شرائية'],
    '/subscriptions': ['اشتراكات شهرية', 'عضويات', 'تجديد الاشتراك', 'جيم أو نادي'],
    '/installments': ['أقساط', 'دفعات مجدولة', 'تحصيل قسط', 'فوائد وتقسيط'],
    '/periodic-maintenance': ['صيانة دورية', 'جدولة الصيانة', 'تذكير الصيانة', 'عقود صيانة'],
    '/crm/leads': ['إدارة العملاء المحتملين', 'الفرص البيعية', 'قمع المبيعات', 'المتابعة'],
    '/crm/tickets': ['تذاكر الدعم الفني', 'شكاوى العملاء', 'متابعة المشكلات'],
    '/crm/campaigns': ['حملات تسويقية', 'رسائل SMS', 'النشرات البريدية'],
    '/customer-portal': ['نظام العملاء', 'تتبع الطلبات للعميل', 'بوابة الدعم'],
    '/products': ['إضافة منتج', 'تعديل الأسعار', 'باركود المنتج', 'الكميات'],
    '/categories': ['إضافة تصنيف', 'تنظيم المنتجات', 'شجرة الأصناف'],
    '/pricing-rules': ['تغيير الأسعار جماعياً', 'تسعير مخصص', 'زيادة الخصومات'],
    '/recipes': ['مكونات الوجبات', 'شجرة المواد BOM', 'تصنيع وتقطيع'],
    '/bom': ['قائمة المواد', 'مكونات التصنيع', 'تكلفة الإنتاج'],
    '/work-centers': ['خطوط الإنتاج', 'مراكز العمل', 'المصنع', 'الماكينات'],
    '/work-orders': ['أوامر الشغل', 'أوامر التصنيع', 'العمليات الإنتاجية'],
    '/quality-control': ['فحص الجودة', 'عينات', 'إتلاف غير المطابق'],
    '/manufacturing/tqm': ['إدارة الجودة الشاملة', 'آيزو', 'معايير الجودة'],
    '/manufacturing/plm': ['دورة حياة المنتج', 'تصميم وتطوير', 'PLM'],
    '/production-planning': ['خطة الإنتاج', 'جدولة التصنيع', 'المواد المطلوبة'],
    '/inventory/demand-forecasting': ['الذكاء الاصطناعي', 'توقع المبيعات', 'تحليل الطلب المستقبلي'],
    '/barcodes': ['طباعة الباركود', 'ليبل المنتجات', 'تصميم الباركود'],
    '/sticker-printing': ['طباعة ملصقات', 'تسعير الرفوف', 'استيكر أسعار'],
    '/restaurant-menu': ['تصميم المنيو', 'قائمة الطعام', 'أصناف المطعم'],
    '/warehouse': ['إدارة المخازن', 'الأرصدة', 'أماكن التخزين', 'الرفوف'],
    '/consignments': ['بضاعة أمانة', 'تخزين للغير', 'بضاعة موردين', 'أمانات منصرفة'],
    '/advanced-wms': ['نظام المخازن المتقدم', 'ممرات التخزين', 'استلام وتوجيه'],
    '/branch-transfers': ['تحويل بضاعة', 'نقل بين الفروع', 'طلبات النقل'],
    '/stock-adjustments': ['تسوية جردية', 'تعديل مخزون', 'بضاعة تالفة', 'هالك'],
    '/inventory-count': ['جرد دوري', 'مطابقة الجرد', 'إدخال جرد'],
    '/purchase-requests': ['طلبات احتياج داخلي', 'طالب شراء', 'نواقص المخزن'],
    '/purchase-orders': ['أوامر الشراء', 'تعميد شراء', 'توثيق طلب مورّد'],
    '/purchases': ['فواتير المشتريات', 'إدخال بضاعة', 'شراء نقدي وآجل'],
    '/suppliers': ['حسابات الموردين', 'كشف حساب مورد', 'دفعات الموردين'],
    '/rfqs': ['عروض أسعار الموردين', 'مناقصات', 'مقارنة الأسعار'],
    '/purchases/supplier-evaluation': ['تقييم المورد', 'أداء الموردين', 'جودة التوريد'],
    '/vendor-portal': ['بوابة الموردين', 'وصول المورد'],
    '/supplier-returns': ['مرتجعات الموردين', 'إشعار مدين', 'رد بضاعة'],
    '/projects': ['إدارة المشاريع', 'المقاولات', 'مستخلصات المشاريع', 'نسبة الإنجاز'],
    '/property-management': ['إدارة الأملاك', 'تأجير', 'العقارات', 'عقود الإيجار'],
    '/tasks': ['إدارة المهام', 'متابعة العمل', 'إنتاجية', 'Task Board'],
    '/events': ['الفعاليات', 'تنظيم معارض', 'حجوزات القاعات'],
    '/tickets': ['التذاكر', 'حجوزات الرحلات', 'المواصلات', 'بطاقات الحضور'],
    '/timesheets': ['سجل الوقت', 'ساعات العمل', 'مشروعية الوقت'],
    '/maintenance': ['أوامر الصيانة', 'صيانة الأعطال', 'فنيين الصيانة'],
    '/computer-mobile-maintenance': ['صيانة الكمبيوتر والموبايل', 'فحص الهواتف', 'قطع غيار اللابتوب', 'حسابات الصيانة وعربونات الأجهزة'],
    '/preventive-maintenance': ['الصيانة الوقائية للآلات', 'جدول الصيانة الدورية'],
    '/fleet': ['إدارة أسطول السيارات', 'الشاحنات', 'تجديد الترخيص', 'صيانة المركبات'],
    '/shipping': ['الشحن المحلي', 'تخليص', 'بوليصة النقل'],
    '/logistics/import-export': ['الاستيراد والتصدير', 'تخليص جمركي', 'بوليصة شحن بحري'],
    '/employees': ['ملف الموظف', 'العاملين', 'بيانات الموظف', 'تحديث بيانات'],
    '/attendance': ['حضور وانصراف', 'بصمة', 'سجلات الدوام', 'غياب'],
    '/shifts': ['ورديات العمل', 'الشيفتات', 'توزيع الورديات'],
    '/leaves': ['الإجازات', 'رصيد إجازات', 'مغادرات', 'إذن انصراف'],
    '/payroll': ['الرواتب', 'اعتماد الرواتب', 'مسيرات الأجور', 'مفردات مرتب'],
    '/hr/commissions': ['عمولات المبيعات', 'الحوافز', 'تارجت عمولة'],
    '/loans': ['سلفيات', 'قروض موظفين', 'خصم القسط'],
    '/benefits': ['البدلات', 'تأمين طبي', 'تذاكر السفر'],
    '/disciplinary': ['الجزاءات', 'إنذارات', 'خصم تأخير', 'تأديب'],
    '/hr/asset-custody': ['عُهد الموظفين', 'تسليم لابتوب', 'جهاز', 'سيارة عهدة'],
    '/org-chart': ['هيكل تنظيمي', 'شجرة الإدارة', 'المناصب'],
    '/recruitment': ['وظائف', 'سير ذاتية', 'توظيف', 'طلبات عمل'],
    '/hr/careers-portal': ['بوابة التوظيف المفتوحة', 'منصة الوظائف'],
    '/onboarding': ['تهيئة الموظف الجديد', 'استقبال موظف'],
    '/performance': ['تقييم الأداء', 'KPIs', 'أهداف الموظف'],
    '/training': ['دورات تدريبية', 'تطوير الموظفين'],
    '/hr/lms': ['نظام إدارة التعلم', 'كورسات داخلية'],
    '/expenses': ['صرف يومية', 'مصاريف', 'سند صرف', 'إيرادات أخرى'],
    '/capital': ['رأس المال', 'حصص الشركاء', 'صندوق التأسيس'],
    '/currencies': ['صرف العملات', 'أسعار الصرف', 'دولار'],
    '/accounting/coa': ['دليل الحسابات', 'شجرة الحسابات', 'تصنيف محاسبي'],
    '/accounting/journal': ['قيود دفترية', 'قيد يومية', 'تسويات'],
    '/accounting/general-ledger': ['دفتر الأستاذ العام', 'كشف حساب رئيسي'],
    '/accounting/cost-centers': ['مراكز التكلفة', 'ربحية فرع', 'تحليل تكلفة'],
    '/accounting/petty-cash': ['عهد نقدية', 'صندوق مالي', 'تصفية عهدة'],
    '/accounting/checks': ['أوراق دفع وقبض', 'شيكات مؤجلة', 'كمبيالات'],
    '/accounting/bank-reconciliation': ['تسويه بنكيه', 'كشف بنكي', 'مطابقة حساب'],
    '/accounting/assets': ['إهلاك الأصول الثابتة', 'شراء أصل'],
    '/accounting/treasury': ['إدارة النقدية', 'تحويل بين الخزن', 'البنوك والصناديق', 'الخزينة', 'الخزينه', 'خزينة'],
    '/accounting/budgeting': ['الموازنة التقديرية', 'تخطيط مالي'],
    '/accounting/aging': ['أعمار الديون', 'متأخرات', 'ديون معدومة'],
    '/accounting/tax': ['إقرار ضريبي', 'القيمة المضافة', 'VAT'],
    '/accounting/e-invoicing': ['فاتورة إلكترونية', 'حسب متطلبات الهيئة'],
    '/accounting/closing': ['ميزانية عمومية', 'تسكير السنة', 'ترحيل أرصدة'],
    '/accounting/reports': ['قائمة الدخل', 'تدفقات نقدية', 'أرباح وخسائر', 'تقارير مالية'],
    '/reports': ['تقارير عامة', 'إحصائيات', 'أنشطة النظام'],
    '/custom-reports': ['بناء تقارير مخصصة', 'منشئ التقارير'],
    '/reports/bi-dashboards': ['ذكاء أعمال BI', 'لوحات تحليل تفاعلية', 'Power BI'],
    '/market-monitor': ['مراقبة الأسعار', 'تحليل سلة السوق'],
    '/settings': ['إعدادات النظام', 'الضرائب', 'الشعار', 'الطابعة'],
    '/branches': ['الفروع', 'تعدد الفروع', 'معلومات الفرع'],
    '/admin/pos-terminals': ['أجهزة الكاشير', 'نقاط البيع', 'Mac Address'],
    '/users': ['إدارة المستخدمين', 'موظفيك بالنظام', 'كلمات المرور'],
    '/role-management': ['صلاحيات المستخدمين', 'وصول مؤمن'],
    '/audit-logs': ['مراقبة النظام', 'سجل الحركات', 'تتبع الأخطاء'],
    '/logbook': ['سجل الأحداث اليومي', 'Log', 'أنشطة'],
    '/system-backups': ['نسخ احتياطي', 'استرجاع بيانات', 'Backup'],
    '/admin/risk-compliance': ['إدارة المخاطر', 'الامتثال للأنظمة'],
    '/law-firm': ['مكاتب المحاماة', 'قضايا', 'جلسات المحكمة', 'موكّلين'],
    '/law-firm/judgments': ['الأحكام والتنفيذ', 'حكم قضائي', 'تأشيرة'],
    '/law-firm/power-of-attorney': ['الوكالات الشرعية', 'توكيل', 'إدارة الوكالة'],
    '/law-firm/consultations': ['استشارات قانونية', 'جلسات استشارية', 'استشارة'],
    '/legal/contracts': ['عقود واتفاقيات قانونية', 'حفظ العقد'],
    '/legal': ['أرشيف المستندات', 'مستندات قانونية', 'أدلة الاثبات'],
    '/approval-workflows': ['مسارات الاعتمادات', 'دورة مستندية'],
    '/dms': ['إدارة الوثائق', 'أرشيف إلكتروني', 'ملفات وسائط'],
    '/internal-communication': ['شات داخلي', 'رسائل النظام', 'تواصل الموظفين'],
    '/website-cms': ['إدارة الموقع الإلكتروني', 'محتوى البوابة'],
    '/about': ['عن النظام', 'إصدار البرنامج'],
    '/recycle-bin': ['سلة المهملات', 'محذوفات', 'استرجاع المحذوفات', 'استرداد'],
    '/customer-display': ['شاشة العميل', 'عرض الطلب للعميل', 'Customer Display'],
    '/school/dashboard': ['إدارة المدرسة', 'نظام المدارس', 'الطلاب'],
    '/school/admissions': ['طلبات الالتحاق', 'انتظار', 'تسجيل'],
    '/school/academic-years': ['الأعوام الدراسية', 'السنة الدراسية'],
    '/school/students': ['سجل الطلاب', 'ملف الطالب', 'بيانات الطلاب'],
    '/school/discounts': ['خصومات', 'منح', 'إعفاءات'],
    '/school/withdrawals': ['انسحاب', 'استرداد', 'إلغاء اشتراك'],
    '/school/secure-pickup': ['استلام آمن', 'تسليم الطفل', 'أشخاص مصرح لهم'],
    '/school/behavior': ['سلوك', 'متابعة نفسية', 'أخصائي'],
    '/school/contracts': ['العقود والموافقات', 'عقد طفل'],
    '/school/teachers': ['المعلمين', 'هيئة التدريس'],
    '/school/classes': ['الفصول', 'الصفوف الدراسية', 'الشُعب'],
    '/school/attendance': ['غياب الطلاب', 'سجل الحضور'],
    '/school/grades': ['الشهادات', 'الامتحانات', 'درجات الطلاب'],
    '/garage/dashboard': ['مركز صيانة السيارات', 'ورشة', 'إصلاح مركبات'],
    '/garage/jobs': ['كارت عمل', 'أمر فحص', 'صيانة سيارة'],
    '/garage/vehicles': ['سيارات العملاء', 'سجل المركبات'],
    '/garage/technicians': ['عمال الورشة', 'فحص السيارات'],
    '/gym/dashboard': ['إدارة الجيم', 'النادي الصحي', 'كمال أجسام'],
    '/gym/memberships': ['اشتراكات الجيم', 'تجديد العضوية', 'باقات'],
    '/gym/classes': ['حصص فتنس', 'يوجا', 'جدول التمارين'],
    '/gym/trainers': ['المدربين الشخصيين', 'كابتن', 'PT'],
    '/hotel/dashboard': ['إدارة الفنادق', 'استقبال فندق', 'شقق مفروشة'],
    '/hotel/reservations': ['حجز غرف', 'تسكين ضيوف', 'مغادرة'],
    '/hotel/rooms': ['حالة الغرف', 'تنظيف الغرف', 'صيانة غرف'],
    '/hotel/housekeeping': ['نظافة الفندق', 'خدمة الغرف'],
    '/helpdesk': ['مركز المساعدة', 'الدعم الفني'],
    '/restaurant/dashboard': ['لوحة تحكم', 'المطعم', 'نظرة عامة'],
    '/restaurant/accounting': ['إيرادات المطعم', 'حسابات المطعم', 'إقفال الصندوق', 'المبيعات النقدية'],
    '/restaurant/reports': ['تقارير المطعم', 'تحليل المبيعات', 'حسب الصنف', 'الأصناف الأكثر مبيعاً'],
    '/restaurant/inventory': ['مخزن المطبخ', 'جرد المطعم', 'خامات', 'نواقص', 'المواد'],
    '/restaurant/employees': ['موظفين المطعم', 'ويتر', 'شيف', 'طاقم العمل'],
    '/clinics': ['العودة للعيادة', 'استقبال', 'مواعيد', 'حجز مريض'],
    '/clinics/patients': ['سجل المرضى', 'ملف طبي', 'تاريخ مرضي', 'أرشيف'],
    '/clinics/doctors': ['الأطباء والجدول', 'مواعيد الأطباء', 'ساعات العمل', 'كشوفات'],
    '/clinics/cockpit': ['عيادة الطبيب', 'لوحة معلومات الطبيب', 'Physician Cockpit', 'كشف مرضي'],
    '/pharmacy/dashboard': ['لوحة الصيدلية', 'نظرة عامة', 'إيرادات الدواء', 'تحليلات الأداء'],
    '/pharmacy/pos': ['بيع أدوية', 'كاشير الصيدلية', 'فاتورة روشتة', 'باركود الدواء', 'دفع نقدي'],
    '/pharmacy/medicines': ['مخزن الأدوية', 'الاسم العلمي', 'البدائل', 'تاريخ انتهاء الصلاحية', 'الدفعات', 'Batch'],
    '/pharmacy/prescriptions': ['صرف روشتة', 'روشتات الأطباء', 'الوصفات الطبية', 'تحويل العيادة'],
    '/pharmacy/purchases': ['شراء أدوية', 'فاتورة المورد', 'توريد مستودع الأدوية', 'نواقص الأدوية'],
    '/pharmacy/reports': ['تقرير صلاحية الأدوية', 'الأدوية المنتهية', 'إحصائيات المبيعات الطبية', 'مكاسب الصيدلية'],
};

export const allNavItems = [
    { 
      label: 'أدوات المطور',
      section: 'developer', 
      items: [
        { path: '/developer/skills', label: 'إدارة أدلة المشاريع (Skills)', icon: FileCode2, roles: ['admin'], modes: ['starter', 'standard', 'service', 'enterprise'] },
        { path: '/developer/chat-logs', label: 'سجلات المحادثات والقرارات', icon: MessageSquare, roles: ['admin'], modes: ['starter', 'standard', 'service', 'enterprise'] },
      ]
    },
    { 
      label: 'نقطة البيع والتشغيل',
      section: 'main', 
      items: [
        { path: '/', label: 'لوحة القيادة', icon: LayoutDashboard, roles: ['admin', 'cashier'], modes: ['starter', 'standard', 'service', 'enterprise'] },
        { path: '/pos', label: 'نقطة البيع', icon: ShoppingCart, roles: ['admin', 'cashier'], modes: ['starter', 'standard', 'service', 'enterprise'] },
        { path: '/wholesale-pos', label: 'شاشة مبيعات الجملة', icon: ShoppingBag, roles: ['admin', 'cashier'], modes: ['standard', 'enterprise'] },
        { path: '/wholesale-ledger', label: 'ترحيل حسابات وقيود الجملة', icon: FileCheck, roles: ['admin'], modes: ['standard', 'enterprise'] },
        { path: '/customer-display', label: 'شاشة العميل', icon: MonitorSmartphone, roles: ['admin', 'cashier'], modes: ['starter', 'standard', 'service', 'enterprise'] },
      ]
    },
    { 
      label: 'نظام التذاكر',
      section: 'ticket_bookings', 
      items: [
        { path: '/tickets/dashboard', label: 'لوحة التحكم', icon: LayoutDashboard, roles: ['admin', 'manager'], modes: ['starter', 'standard', 'service', 'enterprise'] },
        { path: '/tickets', label: 'إدارة الحجوزات', icon: Ticket, roles: ['admin', 'cashier'], modes: ['starter', 'standard', 'service', 'enterprise'] },
        { path: '/tickets/routes', label: 'إدارة الرحلات والخطوط', icon: Route, roles: ['admin', 'manager'], modes: ['starter', 'standard', 'service', 'enterprise'] },
        { path: '/tickets/fleet', label: 'إدارة أسطول النقل', icon: Bus, roles: ['admin', 'manager'], modes: ['starter', 'standard', 'service', 'enterprise'] },
        { path: '/tickets/branches', label: 'فروع المحل والمناديب', icon: Building2, roles: ['admin', 'manager'], modes: ['starter', 'standard', 'service', 'enterprise'] },
        { path: '/tickets/vendors', label: 'الشركات والخطوط', icon: Building2, roles: ['admin', 'manager'], modes: ['starter', 'standard', 'service', 'enterprise'] },
        { path: '/tickets/crm', label: 'الركاب والولاء', icon: Users, roles: ['admin', 'manager', 'cashier'], modes: ['starter', 'standard', 'service', 'enterprise'] },
        { path: '/tickets/cargo', label: 'شحن الطرود', icon: Package, roles: ['admin', 'manager', 'cashier'], modes: ['starter', 'standard', 'service', 'enterprise'] },
        { path: '/tickets/live', label: 'المتابعة الحية', icon: Activity, roles: ['admin', 'manager'], modes: ['enterprise'] },
        { path: '/tickets/manifest', label: 'تطبيق المشرف للموبايل', icon: Smartphone, roles: ['admin', 'manager', 'cashier'], modes: ['starter', 'standard', 'service', 'enterprise'] },
        { path: '/tickets/financials', label: 'الحسابات والخزينة', icon: Wallet, roles: ['admin', 'manager', 'cashier'], modes: ['starter', 'standard', 'service', 'enterprise'] },
        { path: '/tickets/reports', label: 'التقارير والإحصائيات', icon: FileBarChart, roles: ['admin', 'manager'], modes: ['starter', 'standard', 'service', 'enterprise'] },
        { path: '/tickets/settings', label: 'الإعدادات والصلاحيات', icon: Settings, roles: ['admin', 'manager'], modes: ['starter', 'standard', 'service', 'enterprise'] },
      ]
    },
    {
      label: 'المطعم والكافيه',
      section: 'restaurant',
      items: [
        { path: '/restaurant/dashboard', label: 'لوحة التحكم', icon: LayoutDashboard, roles: ['admin', 'manager'], modes: ['standard', 'enterprise'] },
        { path: '/restaurant-pos', label: 'كاشير المطعم', icon: Utensils, roles: ['admin', 'cashier'], modes: ['standard', 'enterprise'] },
        { path: '/call-center', label: 'الكول سنتر', icon: Headset, roles: ['admin', 'cashier'], modes: ['standard', 'enterprise'] },
        { path: '/waiter', label: 'تطبيق النادل', icon: Utensils, roles: ['admin', 'cashier', 'waiter'], modes: ['standard', 'enterprise'] },
        { path: '/kitchen', label: 'شاشة المطبخ', icon: ChefHat, roles: ['admin', 'cashier'], modes: ['standard', 'enterprise'] },
        { path: '/tables', label: 'إدارة الطاولات', icon: LayoutGrid, roles: ['admin', 'cashier'], modes: ['standard', 'enterprise'] }, 
        { path: '/restaurant-menu', label: 'طباعة وتصميم المنيو', icon: BookOpen, roles: ['admin', 'manager'], modes: ['standard', 'enterprise'] },
        { path: '/restaurant/inventory', label: 'إدارة المنيو والمخزون', icon: Package, roles: ['admin', 'manager'], modes: ['standard', 'enterprise'] },
        { path: '/restaurant/accounting', label: 'المبيعات واليومية', icon: Calculator, roles: ['admin', 'manager'], modes: ['standard', 'enterprise'] },
        { path: '/restaurant/reports', label: 'تقارير المطعم', icon: PieChart, roles: ['admin', 'manager'], modes: ['standard', 'enterprise'] },
        { path: '/restaurant/employees', label: 'طاقم المطعم', icon: Users, roles: ['admin', 'manager'], modes: ['standard', 'enterprise'] },
        { path: '/restaurant/attendance', label: 'الدوام والحضور', icon: Clock, roles: ['admin', 'manager'], modes: ['standard', 'enterprise'] },
        { path: '/shifts', label: 'صندوق وورديات الكاشير', icon: Wallet, roles: ['admin', 'manager', 'cashier'], modes: ['standard', 'enterprise'] },
      ]
    },
    {
      label: 'إدارة الملابس والأزياء',
      section: 'clothes',
      items: [
        { path: '/pos', label: 'كاشير المبيعات', icon: ShoppingCart, roles: ['admin', 'cashier'], modes: ['starter', 'standard', 'service', 'enterprise'] },
        { path: '/rentals', label: 'إيجار وحجوزات الملابس', icon: Shirt, roles: ['admin', 'cashier'], modes: ['service', 'enterprise'] },
        { path: '/products', label: 'إدارة الموديلات والمقاسات', icon: Package, roles: ['admin', 'manager'], modes: ['starter', 'standard', 'service', 'enterprise'] },
        { path: '/customers', label: 'سجل العملاء', icon: Users, roles: ['admin', 'cashier'], modes: ['starter', 'standard', 'service', 'enterprise'] },
        { path: '/returns', label: 'الاستبدال والاسترجاع', icon: RotateCcw, roles: ['admin', 'cashier', 'manager'], modes: ['starter', 'standard', 'service', 'enterprise'] },
        { path: '/shifts', label: 'الورديات وإغلاق الكاشير', icon: Clock, roles: ['admin', 'manager'], modes: ['starter', 'standard', 'service', 'enterprise'] },
        { path: '/inventory-count', label: 'جرد ونواقص المحل', icon: ClipboardList, roles: ['admin', 'manager'], modes: ['standard', 'service', 'enterprise'] },
        { path: '/expenses', label: 'المصروفات', icon: Calculator, roles: ['admin', 'manager'], modes: ['starter', 'standard', 'service', 'enterprise'] },
        { path: '/accounting/journal', label: 'الحسابات والقيود', icon: FileText, roles: ['admin'], modes: ['standard', 'service', 'enterprise'] },
        { path: '/reports', label: 'تقارير المبيعات والإيجار', icon: PieChart, roles: ['admin', 'manager'], modes: ['standard', 'service', 'enterprise'] },
      ]
    },
    {
      label: 'قسم التفصيل والخياطة',
      section: 'tailoring',
      items: [
        { path: '/tailoring', label: 'طلبات التفصيل', icon: Edit3, roles: ['admin', 'cashier'], modes: ['service', 'enterprise'] },
        { path: '/customers', label: 'العملاء والمقاسات', icon: Users, roles: ['admin', 'cashier'], modes: ['starter', 'standard', 'service', 'enterprise'] },
        { path: '/products', label: 'المنتجات الجاهزة والخدمات', icon: Package, roles: ['admin', 'manager'], modes: ['starter', 'standard', 'service', 'enterprise'] },
        { path: '/warehouse', label: 'مستودع الأقمشة والخامات', icon: Box, roles: ['admin', 'manager'], modes: ['standard', 'service', 'enterprise'] },
        { path: '/purchases/invoices', label: 'مشتريات الخامات', icon: ShoppingBag, roles: ['admin', 'manager'], modes: ['standard', 'service', 'enterprise'] },
        { path: '/suppliers', label: 'موردين الخامات', icon: Users, roles: ['admin', 'manager'], modes: ['standard', 'service', 'enterprise'] },
        { path: '/employees', label: 'الخياطين والموظفين', icon: Briefcase, roles: ['admin', 'manager'], modes: ['standard', 'service', 'enterprise'] },
        { path: '/shifts', label: 'الورديات واليومية', icon: Clock, roles: ['admin', 'manager'], modes: ['starter', 'standard', 'service', 'enterprise'] },
        { path: '/expenses', label: 'مصروفات المشغل', icon: Calculator, roles: ['admin', 'manager'], modes: ['starter', 'standard', 'service', 'enterprise'] },
        { path: '/accounting/journal', label: 'حسابات المشغل', icon: FileText, roles: ['admin'], modes: ['standard', 'service', 'enterprise'] },
      ]
    },
    {
      label: 'قسم الاستوديو والتصوير',
      section: 'studio',
      items: [
        { path: '/pos', label: 'كاشير المبيعات (اكسسوارات)', icon: ShoppingCart, roles: ['admin', 'cashier'], modes: ['starter', 'standard', 'service', 'enterprise'] },
        { path: '/studio', label: 'حجز ومواعيد الاستوديو', icon: Video, roles: ['admin', 'cashier'], modes: ['starter', 'standard', 'service', 'enterprise'] },
        { path: '/orders', label: 'أوامر الطباعة والمونتاج', icon: Printer, roles: ['admin', 'cashier', 'manager'], modes: ['starter', 'standard', 'service', 'enterprise'] },
        { path: '/customers', label: 'عملاء الاستوديو', icon: Users, roles: ['admin', 'cashier'], modes: ['starter', 'standard', 'service', 'enterprise'] },
        { path: '/products', label: 'إدارة الالبومات والبراويز', icon: Package, roles: ['admin', 'manager'], modes: ['starter', 'standard', 'service', 'enterprise'] },
        { path: '/shifts', label: 'الورديات وإيراد اليوم', icon: Clock, roles: ['admin', 'manager'], modes: ['starter', 'standard', 'service', 'enterprise'] },
        { path: '/employees', label: 'المصورين والمصممين', icon: Briefcase, roles: ['admin', 'manager'], modes: ['standard', 'service', 'enterprise'] },
        { path: '/expenses', label: 'مصروفات الاستوديو', icon: Calculator, roles: ['admin', 'manager'], modes: ['starter', 'standard', 'service', 'enterprise'] },
        { path: '/accounting/journal', label: 'حسابات الاستوديو', icon: FileText, roles: ['admin'], modes: ['standard', 'service', 'enterprise'] },
        { path: '/reports', label: 'تقارير الاستوديو', icon: PieChart, roles: ['admin', 'manager'], modes: ['standard', 'service', 'enterprise'] },
      ]
    },
    {
      label: 'نظام الحضانة وروضة الأطفال',
      section: 'education',
      items: [
        { path: '/school/dashboard', label: 'لوحة التحكم', icon: LayoutDashboard, roles: ['admin', 'manager'], modes: ['enterprise', 'service'] },
        { path: '/school/smart-notifications', label: 'الإشعارات الذكية', icon: Bell, roles: ['admin', 'manager'], modes: ['enterprise', 'service'] },
        { path: '/school/admissions', label: 'طلبات الالتحاق', icon: UserPlus, roles: ['admin', 'manager'], modes: ['enterprise', 'service'] },
        { path: '/school/academic-years', label: 'الأعوام الدراسية', icon: CalendarClock, roles: ['admin', 'manager'], modes: ['enterprise', 'service'] },
        { path: '/school/students', label: 'الأطفال', icon: Users, roles: ['admin', 'manager'], modes: ['enterprise', 'service'] },
        { path: '/school/contracts', label: 'العقود والموافقات', icon: FileCheck, roles: ['admin', 'manager'], modes: ['enterprise', 'service'] },
        { path: '/school/parents', label: 'أولياء الأمور', icon: Users, roles: ['admin', 'manager'], modes: ['enterprise', 'service'] },
        { path: '/school/secure-pickup', label: 'الاستلام الآمن', icon: QrCode, roles: ['admin', 'manager'], modes: ['enterprise', 'service'] },
        { path: '/school/attendance', label: 'الحضور والانصراف', icon: CalendarClock, roles: ['admin', 'manager'], modes: ['enterprise', 'service'] },
        { path: '/school/behavior', label: 'المتابعة السلوكية', icon: Brain, roles: ['admin', 'manager'], modes: ['enterprise', 'service'] },
        { path: '/school/classes', label: 'الفصول والمستويات', icon: BookOpen, roles: ['admin', 'manager'], modes: ['enterprise', 'service'] },
        { path: '/school/fees', label: 'الاشتراكات والفواتير', icon: DollarSign, roles: ['admin', 'manager'], modes: ['enterprise', 'service'] },
        { path: '/school/discounts', label: 'الخصومات والمنح', icon: Percent, roles: ['admin', 'manager'], modes: ['enterprise', 'service'] },
        { path: '/school/withdrawals', label: 'الانسحاب والاسترداد', icon: UserMinus, roles: ['admin', 'manager'], modes: ['enterprise', 'service'] },
        { path: '/school/cashier', label: 'الخزنة والمدفوعات', icon: WalletCards, roles: ['admin', 'manager'], modes: ['enterprise', 'service'] },
        { path: '/school/expenses', label: 'المصروفات المنصرفة', icon: WalletCards, roles: ['admin', 'manager'], modes: ['enterprise', 'service'] },
        { path: '/accounting', label: 'الخزنة والإيرادات (عام)', icon: WalletCards, roles: ['admin', 'manager'], modes: ['enterprise', 'service'] },
        { path: '/school/employees', label: 'المشرفات والموظفون', icon: Briefcase, roles: ['admin', 'manager'], modes: ['enterprise', 'service'] },
        { path: '/expenses', label: 'المصروفات والمرتبات', icon: Calculator, roles: ['admin', 'manager'], modes: ['enterprise', 'service'] },
        { path: '/school/transport', label: 'الباص والمواصلات', icon: Truck, roles: ['admin', 'manager'], modes: ['enterprise', 'service'] },
        { path: '/school/grades', label: 'التقييمات التعليمية', icon: FileCheck, roles: ['admin', 'manager'], modes: ['enterprise', 'service'] },
        { path: '/school/exams', label: 'الاختبارات والتقييمات', icon: FileCheck, roles: ['admin', 'manager'], modes: ['enterprise', 'service'] },
        { path: '/school/meals', label: 'الوجبات والتغذية', icon: Salad, roles: ['admin', 'manager'], modes: ['enterprise', 'service'] },
        { path: '/school/sleep', label: 'راحة الطفل والنوم', icon: Moon, roles: ['admin', 'manager'], modes: ['enterprise', 'service'] },
        { path: '/school/daily-reports', label: 'التقرير اليومي', icon: FileText, roles: ['admin', 'manager'], modes: ['enterprise', 'service'] },
        { path: '/school/gallery', label: 'معرض الصور', icon: Camera, roles: ['admin', 'manager'], modes: ['enterprise', 'service'] },
        { path: '/school/inventory', label: 'المخزون والعهد', icon: Package, roles: ['admin', 'manager'], modes: ['enterprise', 'service'] },
        { path: '/school/suppliers', label: 'الموردين', icon: Store, roles: ['admin', 'manager'], modes: ['enterprise', 'service'] },
        { path: '/school/complaints', label: 'الشكاوى والملاحظات', icon: AlertTriangle, roles: ['admin', 'manager'], modes: ['enterprise', 'service'] },
        { path: '/school/clinic', label: 'الصحة والعيادة', icon: Activity, roles: ['admin', 'manager'], modes: ['enterprise', 'service'] },
        { path: '/school/trips', label: 'الرحلات المدرسية', icon: Truck, roles: ['admin', 'manager'], modes: ['enterprise', 'service'] },
        { path: '/school/activities', label: 'الأنشطة اليومية', icon: FileText, roles: ['admin', 'manager'], modes: ['enterprise', 'service'] },
        { path: '/school/events', label: 'الأحداث والتقويم', icon: CalendarClock, roles: ['admin', 'manager'], modes: ['enterprise', 'service'] },
        { path: '/school/parent-communication', label: 'الرسائل والإشعارات', icon: MessageCircle, roles: ['admin', 'manager'], modes: ['enterprise', 'service'] },
        { path: '/school/reports', label: 'تقارير الحضانة والمدرسة', icon: PieChart, roles: ['admin', 'manager'], modes: ['enterprise', 'service'] },
        { path: '/settings', label: 'الإعدادات والصلاحيات', icon: Settings, roles: ['admin', 'manager'], modes: ['enterprise', 'service'] },
      ]
    },
    {
      label: 'الورش ومراكز الصيانة',
      section: 'garage',
      items: [
        { path: '/garage/dashboard', label: 'لوحة الورشة', icon: LayoutDashboard, roles: ['admin'], modes: ['enterprise', 'service'] },
        { path: '/garage/jobs', label: 'بطاقات العمل (Job Cards)', icon: ClipboardList, roles: ['admin', 'manager'], modes: ['enterprise', 'service'] },
        { path: '/garage/vehicles', label: 'المركبات', icon: Truck, roles: ['admin', 'manager'], modes: ['enterprise', 'service'] },
        { path: '/garage/technicians', label: 'الفنيون', icon: Wrench, roles: ['admin', 'manager'], modes: ['enterprise', 'service'] },
        { path: '/garage/spare-parts', label: 'قطع الغيار', icon: Settings, roles: ['admin', 'manager'], modes: ['enterprise', 'service'] },
        { path: '/garage/appointments', label: 'حجز المواعيد', icon: CalendarClock, roles: ['admin', 'manager'], modes: ['enterprise', 'service'] },
        { path: '/garage/invoices', label: 'فواتير الصيانة', icon: FileText, roles: ['admin', 'manager'], modes: ['enterprise', 'service'] },
        { path: '/garage/employees', label: 'طاقم العمل', icon: Users, roles: ['admin', 'manager'], modes: ['enterprise', 'service'] },
        { path: '/garage/attendance', label: 'حضور الفنيين', icon: Clock, roles: ['admin', 'manager'], modes: ['enterprise', 'service'] },
      ]
    },
    {
      label: 'صيانة الكمبيوتر والموبايل',
      section: 'computer_mobile_maintenance',
      items: [
        { path: '/computer-mobile-maintenance/dashboard', label: 'لوحة التحكم والتحليل', icon: LayoutDashboard, roles: ['admin', 'cashier'], modes: ['standard', 'service', 'enterprise'] },
        { path: '/computer-mobile-maintenance/orders', label: 'كروت وأجهزة الصيانة', icon: ClipboardList, roles: ['admin', 'cashier'], modes: ['standard', 'service', 'enterprise'] },
        { path: '/computer-mobile-maintenance/express', label: '⚡ صيانة فورية (انتظار العميل)', icon: Zap, roles: ['admin', 'cashier'], modes: ['standard', 'service', 'enterprise'] },
        { path: '/computer-mobile-maintenance/parts', label: 'مستودع قطع الغيار', icon: DatabaseBackup, roles: ['admin', 'cashier'], modes: ['standard', 'service', 'enterprise'] },
        { path: '/computer-mobile-maintenance/technicians', label: 'تكليفات الفنيين', icon: Users, roles: ['admin', 'cashier'], modes: ['standard', 'service', 'enterprise'] },
        { path: '/computer-mobile-maintenance/financials', label: 'الحركة المحاسبية والقيود', icon: Scale, roles: ['admin', 'cashier'], modes: ['standard', 'service', 'enterprise'] },
        { path: '/computer-mobile-maintenance/delivery', label: 'شاشة تسليم الأجهزة والضمان', icon: ClipboardCheck, roles: ['admin', 'cashier'], modes: ['standard', 'service', 'enterprise'] },
        { path: '/computer-mobile-maintenance/shelves', label: 'حركة الأجهزة والرفوف', icon: MapPin, roles: ['admin', 'cashier'], modes: ['standard', 'service', 'enterprise'] },
        { path: '/computer-mobile-maintenance/approvals', label: 'موافقات العملاء والتسعير', icon: MessageSquare, roles: ['admin', 'cashier'], modes: ['standard', 'service', 'enterprise'] },
        { path: '/computer-mobile-maintenance/rma', label: 'إدارة الضمان ولوجستيات RMA', icon: ShieldCheck, roles: ['admin', 'cashier'], modes: ['standard', 'service', 'enterprise'] },
        { path: '/computer-mobile-maintenance/abandoned', label: 'إدارة الأجهزة المهملة والكهنة', icon: AlertOctagon, roles: ['admin', 'cashier'], modes: ['standard', 'service', 'enterprise'] },
        { path: '/computer-mobile-maintenance/outsourcing', label: 'كروت الصيانة الخارجية والـ Outsourcing', icon: Network, roles: ['admin', 'cashier'], modes: ['standard', 'service', 'enterprise'] },
        { path: '/computer-mobile-maintenance/couriers', label: 'لوجستيات الشحن وإدارة المناديب 🚚', icon: Truck, roles: ['admin', 'cashier'], modes: ['standard', 'service', 'enterprise'] },
        { path: '/computer-mobile-maintenance/b2b-contracts', label: 'باقات اشتراكات وصيانة الشركات B2B 🏢', icon: Briefcase, roles: ['admin', 'cashier'], modes: ['standard', 'service', 'enterprise'] },
        { path: '/computer-mobile-maintenance/internal-tools', label: 'مخزن العُهد وأدوات الورشة الداخليّة 🛠️', icon: Wrench, roles: ['admin', 'cashier'], modes: ['standard', 'service', 'enterprise'] },
        { path: '/computer-mobile-maintenance/offline-sync', label: 'لوجستية المزامنة والعمل الأوفلاين 🔄', icon: RefreshCw, roles: ['admin', 'cashier'], modes: ['standard', 'service', 'enterprise'] },
      ]
    },
    {
      label: 'الأندية الرياضية (الجيم)',
      section: 'gym',
      items: [
        { path: '/gym/dashboard', label: 'لوحة النادي', icon: LayoutDashboard, roles: ['admin'], modes: ['enterprise', 'service'] },
        { path: '/gym/memberships', label: 'عضويات النادي', icon: Users, roles: ['admin', 'manager'], modes: ['enterprise', 'service'] },
        { path: '/gym/classes', label: 'الحصص الرياضية', icon: CalendarDays, roles: ['admin', 'manager'], modes: ['enterprise', 'service'] },
        { path: '/gym/trainers', label: 'المدربون', icon: CircleUser, roles: ['admin', 'manager'], modes: ['enterprise', 'service'] },
        { path: '/gym/equipment', label: 'صيانة الأجهزة', icon: Wrench, roles: ['admin', 'manager'], modes: ['enterprise', 'service'] },
        { path: '/gym/store', label: 'مبيعات الجيم', icon: ShoppingCart, roles: ['admin', 'manager'], modes: ['enterprise', 'service'] },
        { path: '/gym/access-control', label: 'سجل الدخول', icon: ShieldCheck, roles: ['admin', 'manager'], modes: ['enterprise', 'service'] },
        { path: '/gym/employees', label: 'الموظفون', icon: Users, roles: ['admin', 'manager'], modes: ['enterprise', 'service'] },
        { path: '/gym/attendance', label: 'حضور المدربين', icon: Clock, roles: ['admin', 'manager'], modes: ['enterprise', 'service'] },
      ]
    },
    {
      label: 'الفنادق والضيافة',
      section: 'hotel',
      items: [
        { path: '/hotel/dashboard', label: 'لوحة الفندق', icon: LayoutDashboard, roles: ['admin'], modes: ['enterprise', 'service'] },
        { path: '/hotel/reservations', label: 'الحجوزات', icon: CalendarClock, roles: ['admin', 'manager'], modes: ['enterprise', 'service'] },
        { path: '/hotel/rooms', label: 'الغرف والمرافق', icon: Building2, roles: ['admin', 'manager'], modes: ['enterprise', 'service'] },
        { path: '/hotel/housekeeping', label: 'التدبير الفندقي', icon: ShieldCheck, roles: ['admin', 'manager'], modes: ['enterprise', 'service'] },
        { path: '/hotel/services', label: 'الخدمات الإضافية', icon: Settings, roles: ['admin', 'manager'], modes: ['enterprise', 'service'] },
        { path: '/hotel/dining', label: 'مطعم الفندق', icon: Coffee, roles: ['admin', 'manager'], modes: ['enterprise', 'service'] },
        { path: '/hotel/billing', label: 'فواتير النزلاء', icon: FileText, roles: ['admin', 'manager'], modes: ['enterprise', 'service'] },
        { path: '/hotel/employees', label: 'شؤون الموظفين', icon: Users, roles: ['admin', 'manager'], modes: ['enterprise', 'service'] },
        { path: '/hotel/attendance', label: 'حضور طاقم الفندق', icon: Clock, roles: ['admin', 'manager'], modes: ['enterprise', 'service'] },
      ]
    },
    { 
      label: 'العيادات والمراكز الطبية',
      section: 'clinics',
      items: [
        { path: '/clinics/dashboard', label: 'لوحة التحكم', icon: LayoutDashboard, roles: ['admin'], modes: ['service', 'enterprise'] },
        { path: '/clinics', label: 'الاستقبال و المواعيد', icon: Activity, roles: ['admin', 'cashier'], modes: ['service', 'enterprise'] },
        { path: '/clinics/patients', label: 'سجل المرضى', icon: Users, roles: ['admin', 'cashier'], modes: ['service', 'enterprise'] },
        { path: '/clinics/doctors', label: 'الأطباء والجدول', icon: Briefcase, roles: ['admin', 'cashier'], modes: ['service', 'enterprise'] },
        { path: '/clinics/cockpit', label: 'عيادة الطبيب (Cockpit)', icon: Activity, roles: ['admin', 'manager'], modes: ['service', 'enterprise'] },
        { path: '/clinics/billing', label: 'المالية والفواتير', icon: FileText, roles: ['admin', 'manager'], modes: ['service', 'enterprise'] },
        { path: '/clinics/inventory', label: 'المخزن الطبي', icon: ShoppingCart, roles: ['admin', 'manager'], modes: ['service', 'enterprise'] },
        { path: '/clinics/assets', label: 'إدارة الأصول والصيانة', icon: Wrench, roles: ['admin', 'manager'], modes: ['service', 'enterprise'] },
        { path: '/clinics/services', label: 'الخدمات الطبية', icon: Settings, roles: ['admin', 'manager'], modes: ['service', 'enterprise'] },
        { path: '/clinics/insurance', label: 'شركات التأمين', icon: ShieldCheck, roles: ['admin', 'manager'], modes: ['service', 'enterprise'] },
        { path: '/clinics/reports', label: 'التقارير الطبية', icon: FileClock, roles: ['admin', 'manager'], modes: ['service', 'enterprise'] },
        { path: '/clinics/employees', label: 'طاقم العيادة', icon: Users, roles: ['admin', 'manager'], modes: ['service', 'enterprise'] },
        { path: '/clinics/attendance', label: 'حضور الطاقم الطبي', icon: Clock, roles: ['admin', 'manager'], modes: ['service', 'enterprise'] },
      ]
    },
    {
      label: 'الصيدلية وإدارة الدواء',
      section: 'pharmacy',
      items: [
        { path: '/pharmacy/dashboard', label: 'لوحة التحكم للصيدلية', icon: LayoutDashboard, roles: ['admin'], modes: ['service', 'enterprise'] },
        { path: '/pharmacy/pos', label: 'كاشير الصيدلية (POS)', icon: ShoppingCart, roles: ['admin', 'cashier'], modes: ['starter', 'standard', 'service', 'enterprise'] },
        { path: '/pharmacy/medicines', label: 'دليل المنتجات والأدوية', icon: Package, roles: ['admin', 'manager'], modes: ['starter', 'standard', 'service', 'enterprise'] },
        { path: '/pharmacy/prescriptions', label: 'صرف الروشتات والوصفات', icon: FileCheck, roles: ['admin', 'cashier', 'manager'], modes: ['starter', 'standard', 'service', 'enterprise'] },
        { path: '/pharmacy/purchases', label: 'مشتريات وتوريد الأدوية', icon: Landmark, roles: ['admin', 'manager'], modes: ['standard', 'enterprise'] },
        { path: '/pharmacy/reports', label: 'تقارير الأدوية والصلاحية', icon: FileBarChart, roles: ['admin', 'manager'], modes: ['service', 'enterprise'] },
      ]
    },
    {
      label: 'إدارة مزارع البقر',
      section: 'cow_farm',
      items: [
        { path: '/cow-farm', label: 'لوحة التحكم للمزرعة', icon: LayoutDashboard, roles: ['admin', 'manager'], modes: ['starter', 'standard', 'service', 'enterprise'] },
        { path: '/cow-farm/cows', label: 'إدارة الأبقار (القطيع)', icon: Activity, roles: ['admin', 'manager'], modes: ['starter', 'standard', 'service', 'enterprise'] },
        { path: '/cow-farm/milk', label: 'إنتاج ومصنع الألبان', icon: FileCheck, roles: ['admin', 'manager', 'cashier'], modes: ['starter', 'standard', 'service', 'enterprise'] },
        { path: '/cow-farm/breeding', label: 'التلقيح والتناسل', icon: CalendarClock, roles: ['admin', 'manager'], modes: ['starter', 'standard', 'service', 'enterprise'] },
        { path: '/cow-farm/health', label: 'التحصينات والعيادة البيطرية', icon: HeartHandshake, roles: ['admin', 'manager'], modes: ['starter', 'standard', 'service', 'enterprise'] },
        { path: '/cow-farm/feed', label: 'إدارة الأعلاف والتغذية', icon: Warehouse, roles: ['admin', 'manager', 'warehouse'], modes: ['starter', 'standard', 'service', 'enterprise'] },
        { path: '/cow-farm/financials', label: 'المعاملات المالية والقيود', icon: Wallet, roles: ['admin', 'manager'], modes: ['starter', 'standard', 'service', 'enterprise'] },
      ]
    },
    {
      label: 'المبيعات والطلبات',
      section: 'sales', 
      items: [
        { path: '/orders', label: 'المبيعات', icon: History, roles: ['admin', 'cashier'], modes: ['starter', 'standard', 'service', 'enterprise'] },
        { path: '/quotations', label: 'عروض الأسعار', icon: FileClock, roles: ['admin', 'cashier'], modes: ['service', 'standard', 'enterprise'] },
        { path: '/b2b-sales', label: 'مبيعات الجملة', icon: FileText, roles: ['admin', 'cashier'], modes: ['standard', 'enterprise'] },
        { path: '/ecommerce', label: 'طلبات المتجر', icon: ShoppingCart, roles: ['admin', 'cashier'], modes: ['standard', 'enterprise'] },
        { path: '/layaways', label: 'نظام العربون والحجز', icon: Bookmark, roles: ['admin', 'cashier'], modes: ['standard', 'enterprise'] },
        { path: '/returns', label: 'المرتجعات', icon: RotateCcw, roles: ['admin', 'cashier'], modes: ['standard', 'enterprise'] },
        { path: '/commodity-contracts', label: 'حجوزات البضائع', icon: Layers, roles: ['admin', 'cashier'], modes: ['standard', 'enterprise'] },
      ]
    },
    {
      label: 'فريق المبيعات والتوزيع',
      section: 'sales_team',
      items: [
        { path: '/van-sales', label: 'مبيعات المندوبين', icon: Truck, roles: ['admin'], modes: ['enterprise'] },
        { path: '/sales-targets', label: 'أهداف المبيعات', icon: Target, roles: ['admin'], modes: ['enterprise'] },
      ]
    },
    { 
      label: 'العملاء وبرامج الولاء',
      section: 'customers', 
      items: [
        { path: '/customers', label: 'العملاء', icon: Users, roles: ['admin', 'cashier'], modes: ['standard', 'service', 'enterprise'] },
        { path: '/loyalty', label: 'برنامج الولاء', icon: Star, roles: ['admin', 'cashier'], modes: ['standard', 'enterprise'] },
        { path: '/promotions', label: 'العروض الترويجية', icon: Percent, roles: ['admin', 'cashier'], modes: ['standard', 'enterprise'] },
        { path: '/gift-cards', label: 'بطاقات الهدايا', icon: Gift, roles: ['admin', 'cashier'], modes: ['standard', 'enterprise'] },
        { path: '/subscriptions', label: 'الاشتراكات', icon: Repeat, roles: ['admin', 'cashier'], modes: ['service', 'enterprise'] },
        { path: '/installments', label: 'إدارة الأقساط', icon: CalendarClock, roles: ['admin', 'cashier'], modes: ['standard', 'enterprise'] },
      ]
    },
    {
      label: 'إدارة علاقات العملاء (CRM)',
      section: 'crm',
      items: [
        { path: '/crm/leads', label: 'الفرص والمبيعات', icon: Filter, roles: ['admin', 'cashier'], modes: ['enterprise'] },
        { path: '/crm/campaigns', label: 'الحملات التسويقية', icon: Megaphone, roles: ['admin'], modes: ['enterprise'] },
        { path: '/crm/tickets', label: 'الدعم الفني', icon: LifeBuoy, roles: ['admin', 'cashier'], modes: ['standard', 'service', 'enterprise'] },
        { path: '/customer-portal', label: 'بوابة العملاء', icon: CircleUser, roles: ['admin', 'cashier'], modes: ['enterprise'] },
      ]
    },
    { 
      label: 'إدارة المنتجات',
      section: 'products', 
      items: [
        { path: '/products', label: 'المنتجات', icon: Package, roles: ['admin', 'warehouse'], modes: ['starter', 'standard', 'service', 'enterprise'] },
        { path: '/categories', label: 'التصنيفات', icon: Layers, roles: ['admin', 'warehouse'], modes: ['starter', 'standard', 'service', 'enterprise'] },
        { path: '/measurement-units', label: 'وحدات القياس الاستراتيجية', icon: Box, roles: ['admin', 'warehouse'], modes: ['standard', 'service', 'enterprise'] },
        { path: '/product-price-history', label: 'سجل الأسعار والتكلفة', icon: History, roles: ['admin'], modes: ['enterprise'] },
        { path: '/pricing-rules', label: 'قواعد التسعير', icon: Banknote, roles: ['admin'], modes: ['standard', 'enterprise'] },
        { path: '/barcodes', label: 'طباعة الباركود', icon: ScanLine, roles: ['admin', 'warehouse'], modes: ['standard', 'service', 'enterprise'] },
        { path: '/sticker-printing', label: 'ملصقات المنتجات', icon: Printer, roles: ['admin', 'warehouse'], modes: ['service', 'enterprise'] },
        { path: '/periodic-maintenance', label: 'صيانة المنتجات', icon: Wrench, roles: ['admin', 'cashier'], modes: ['standard', 'service', 'enterprise'] },
      ]
    },
    {
      label: 'التصنيع والإنتاج',
      section: 'manufacturing',
      items: [
        { path: '/recipes', label: 'الوصفات (BOM)', icon: Utensils, roles: ['admin', 'warehouse'], modes: ['standard', 'enterprise'] },
        { path: '/bom', label: 'قائمة المواد (BOM)', icon: Factory, roles: ['admin', 'warehouse'], modes: ['standard', 'enterprise'] },
        { path: '/production-planning', label: 'تخطيط الإنتاج', icon: Calendar, roles: ['admin', 'warehouse'], modes: ['standard', 'enterprise'] },
        { path: '/work-orders', label: 'أوامر التشغيل', icon: Settings, roles: ['admin', 'warehouse'], modes: ['standard', 'enterprise'] },
        { path: '/work-centers', label: 'مراكز العمل', icon: Building2, roles: ['admin', 'warehouse'], modes: ['standard', 'enterprise'] },
        { path: '/quality-control', label: 'مراقبة الجودة', icon: ClipboardCheck, roles: ['admin', 'warehouse'], modes: ['standard', 'enterprise'] },
        { path: '/manufacturing/tqm', label: 'إدارة الجودة (TQM)', icon: ShieldCheck, roles: ['admin', 'warehouse'], modes: ['enterprise'] },
        { path: '/manufacturing/plm', label: 'دورة حياة المنتج (PLM)', icon: Layers, roles: ['admin', 'warehouse'], modes: ['enterprise'] },
        { path: '/manufacturing/employees', label: 'طاقم المصنع', icon: Users, roles: ['admin', 'warehouse'], modes: ['enterprise'] },
        { path: '/manufacturing/attendance', label: 'حضور عمال المصنع', icon: Clock, roles: ['admin', 'warehouse'], modes: ['enterprise'] },
      ]
    },
    { 
      label: 'المستودعات والمخزون',
      section: 'inventory', 
      items: [
        { path: '/warehouse', label: 'المستودعات والمخازن', icon: Store, roles: ['admin', 'warehouse'], modes: ['enterprise'] }, 
        { path: '/consignments', label: 'بضاعة الأمانة', icon: Package, roles: ['admin', 'warehouse'], modes: ['enterprise'] },
        { path: '/proactive-low-stock-alerts', label: 'تنبيه نقص المخزون', icon: AlertOctagon, roles: ['admin', 'warehouse'], modes: ['enterprise'] },
        { path: '/advanced-wms', label: 'إدارة المخازن المتقدمة', icon: Package, roles: ['admin', 'warehouse'], modes: ['enterprise'] },
        { path: '/branch-transfers', label: 'تحويلات الفروع', icon: ArrowLeftRight, roles: ['admin', 'warehouse'], modes: ['enterprise'] },
        { path: '/inventory/branch-shipments', label: 'تتبع الشحنات المتبادلة', icon: Truck, roles: ['admin', 'warehouse'], modes: ['enterprise'] },
        { path: '/stock-adjustments', label: 'تسوية المخزون', icon: ClipboardX, roles: ['admin', 'warehouse'], modes: ['enterprise'] },
        { path: '/inventory-count', label: 'الجرد الدوري', icon: ClipboardCheck, roles: ['admin', 'warehouse'], modes: ['enterprise'] },
        { path: '/inventory/expiry-management', label: 'إدارة تاريخ الصلاحية', icon: CalendarX, roles: ['admin', 'warehouse'], modes: ['enterprise'] },
        { path: '/inventory/demand-forecasting', label: 'توقعات الطلب (AI)', icon: TrendingUp, roles: ['admin', 'warehouse'], modes: ['enterprise'] },
        { path: '/inventory/turnover-dashboard', label: 'دوران المخزون', icon: Activity, roles: ['admin', 'warehouse'], modes: ['enterprise'] },
      ]
    },
    {
      label: 'المشتريات والموردين',
      section: 'purchases',
      items: [
        { path: '/purchase-requests', label: 'طلبات الشراء الداخلية', icon: FileText, roles: ['admin', 'warehouse', 'cashier'], modes: ['enterprise'] },
        { path: '/purchase-orders', label: 'أوامر الشراء', icon: FileText, roles: ['admin', 'warehouse'], modes: ['enterprise'] },
        { path: '/purchases', label: 'المشتريات', icon: ClipboardList, roles: ['admin', 'warehouse'], modes: ['standard', 'enterprise'] },
        { path: '/suppliers', label: 'الموردين', icon: Truck, roles: ['admin', 'warehouse'], modes: ['standard', 'enterprise'] },
        { path: '/rfqs', label: 'عروض أسعار الموردين', icon: FileSearch, roles: ['admin', 'warehouse'], modes: ['enterprise'] },
        { path: '/purchases/supplier-evaluation', label: 'تقييم الموردين', icon: Star, roles: ['admin', 'warehouse'], modes: ['enterprise'] },
        { path: '/vendor-portal', label: 'بوابة الموردين', icon: Store, roles: ['admin', 'warehouse'], modes: ['enterprise'] },
        { path: '/supplier-returns', label: 'المرتجعات للموردين', icon: ArrowLeftRight, roles: ['admin', 'warehouse'], modes: ['enterprise'] },
      ]
    },
    {
      label: 'الشحن واللوجستيات',
      section: 'logistics',
      items: [
        { path: '/delivery', label: 'إدارة التوصيل', icon: Truck, roles: ['admin', 'cashier'], modes: ['standard', 'enterprise'] },
        { path: '/fulfillment', label: 'تجهيز الطلبات', icon: ListChecks, roles: ['admin', 'cashier', 'warehouse'], modes: ['enterprise'] }, 
        { path: '/shipping', label: 'الشحن والتخليص', icon: Ship, roles: ['admin', 'warehouse'], modes: ['enterprise', 'standard'] },
        { path: '/fleet', label: 'إدارة المركبات', icon: Truck, roles: ['admin', 'warehouse'], modes: ['enterprise', 'standard'] },
        { path: '/logistics/import-export', label: 'الاستيراد والتصدير', icon: Ship, roles: ['admin', 'warehouse'], modes: ['enterprise'] },
      ]
    },
    {
      label: 'المشاريع والتشغيل',
      section: 'projects',
      items: [
        { path: '/projects', label: 'المشاريع والمقاولات', icon: Briefcase, roles: ['admin'], modes: ['enterprise', 'service'] },
        { path: '/projects/kpis', label: 'مؤشرات الأداء (KPIs)', icon: Target, roles: ['admin'], modes: ['enterprise', 'service'] },
        { path: '/projects/feasibility', label: 'دراسات الجدوى', icon: FileText, roles: ['admin'], modes: ['enterprise', 'service'] },
        { path: '/property-management', label: 'إدارة الممتلكات', icon: Building2, roles: ['admin'], modes: ['enterprise'] },
        { path: '/tasks', label: 'إدارة المهام', icon: ListTodo, roles: ['admin', 'cashier'], modes: ['enterprise', 'service'] },
        { path: '/events', label: 'إدارة الفعاليات', icon: CalendarDays, roles: ['admin'], modes: ['enterprise', 'service'] },
        { path: '/maintenance', label: 'أوامر الصيانة', icon: Wrench, roles: ['admin', 'cashier'], modes: ['service', 'enterprise'] },
        { path: '/preventive-maintenance', label: 'الصيانة الوقائية', icon: Calendar, roles: ['admin'], modes: ['enterprise'] },
        { path: '/property/employees', label: 'إدارة الموظفين', icon: Users, roles: ['admin'], modes: ['enterprise'] },
        { path: '/property/attendance', label: 'حضور موظفي العقارات', icon: Clock, roles: ['admin'], modes: ['enterprise'] },
      ]
    },
    { 
      label: 'الموارد البشرية (Core HR)',
      section: 'hr_core', 
      items: [
        { path: '/employees', label: 'ملفات الموظفين', icon: CircleUser, roles: ['admin'], modes: ['standard', 'enterprise'] },
        { path: '/org-chart', label: 'الهيكل التنظيمي', icon: Users, roles: ['admin'], modes: ['standard', 'enterprise'] },
        { path: '/hr/documents', label: 'إدارة الوثائق', icon: FileText, roles: ['admin'], modes: ['standard', 'enterprise'] },
        { path: '/hr/turnover-dashboard', label: 'معدل الدوران (Turnover)', icon: TrendingDown, roles: ['admin'], modes: ['standard', 'enterprise'] },
        { path: '/hr/payslips', label: 'أرشيف قسائم الرواتب', icon: FileText, roles: ['admin'], modes: ['standard', 'enterprise'] },
        { path: '/hr/annual-bonuses', label: 'المكافآت السنوية', icon: Award, roles: ['admin'], modes: ['standard', 'enterprise'] },
        { path: '/hr/labor-cost-analysis', label: 'تحليل تكلفة العمالة', icon: Activity, roles: ['admin'], modes: ['standard', 'enterprise'] },
        { path: '/employee-portal', label: 'بوابة الموظفين', icon: CircleUser, roles: ['admin', 'cashier', 'warehouse', 'waiter', 'kitchen', 'delivery', 'manager'], modes: ['starter', 'standard', 'service', 'enterprise'] },
        { path: '/attendance', label: 'الحضور والانصراف', icon: Clock, roles: ['admin'], modes: ['standard', 'enterprise'] },
        { path: '/timesheets', label: 'سجلات الوقت', icon: Clock, roles: ['admin', 'cashier'], modes: ['enterprise', 'service'] },
        { path: '/hr/shifts', label: 'ورديات الدوام (Shifts)', icon: CalendarDays, roles: ['admin'], modes: ['standard', 'service', 'enterprise'] },
        { path: '/shifts', label: 'إدارة ورديات الصندوق', icon: LockKeyhole, roles: ['admin', 'cashier'], modes: ['standard', 'service', 'enterprise', 'starter'] },
        { path: '/leaves', label: 'الإجازات والمغادرات', icon: Calendar, roles: ['admin', 'cashier'], modes: ['standard', 'enterprise'] },
      ]
    },
    {
      label: 'الرواتب والمزايا',
      section: 'hr_payroll',
      items: [
        { path: '/payroll', label: 'الرواتب والأجور', icon: Banknote, roles: ['admin'], modes: ['standard', 'service', 'enterprise'] }, 
        { path: '/hr/commissions', label: 'العمولات والحوافز', icon: Coins, roles: ['admin'], modes: ['enterprise'] },
        { path: '/loans', label: 'السلف والقروض', icon: Banknote, roles: ['admin', 'cashier'], modes: ['standard', 'enterprise'] },
        { path: '/benefits', label: 'المزايا والتعويضات', icon: HeartHandshake, roles: ['admin'], modes: ['standard', 'enterprise'] },
      ]
    },
    {
      label: 'إدارة المواهب وتطويرها',
      section: 'hr_talent',
      items: [
        { path: '/recruitment', label: 'التوظيف', icon: Briefcase, roles: ['admin'], modes: ['standard', 'enterprise'] },
        { path: '/hr/careers-portal', label: 'بوابة التوظيف', icon: Globe, roles: ['admin'], modes: ['enterprise'] },
        { path: '/onboarding', label: 'تهيئة الموظفين', icon: UserPlus, roles: ['admin'], modes: ['standard', 'enterprise'] },
        { path: '/performance', label: 'تقييم الأداء', icon: Target, roles: ['admin'], modes: ['standard', 'enterprise'] },
        { path: '/training', label: 'التدريب والتطوير', icon: BookOpen, roles: ['admin'], modes: ['standard', 'enterprise'] },
        { path: '/hr/lms', label: 'نظام التعلم (LMS)', icon: BookOpen, roles: ['admin'], modes: ['enterprise'] },
        { path: '/hr/skills-gap', label: 'تحليل فجوة المهارات', icon: Target, roles: ['admin'], modes: ['enterprise'] },
        { path: '/hr/succession-planning', label: 'تخطيط التعاقب', icon: Network, roles: ['admin'], modes: ['enterprise'] },
        { path: '/hr/surveys', label: 'استبيانات الموظفين', icon: MessageSquare, roles: ['admin'], modes: ['enterprise'] },
        { path: '/disciplinary', label: 'الإجراءات التأديبية', icon: AlertOctagon, roles: ['admin'], modes: ['standard', 'enterprise'] },
        { path: '/hr/asset-custody', label: 'العهد العينية', icon: Laptop, roles: ['admin'], modes: ['enterprise'] },
      ]
    },
    { 
      label: 'المالية والمحاسبة',
      section: 'accounting', 
      items: [
        { path: '/expenses', label: 'المصروفات', icon: Wallet, roles: ['admin'], modes: ['standard', 'service', 'enterprise'] },
        { path: '/capital', label: 'رأس المال', icon: Landmark, roles: ['admin'], modes: ['enterprise'] },
        { path: '/currencies', label: 'العملات', icon: Banknote, roles: ['admin'], modes: ['standard', 'enterprise'] },
        { path: '/accounting/coa', label: 'دليل الحسابات', icon: BookOpen, roles: ['admin'], condition: 'accountingEnabled', modes: ['enterprise'] },
        { path: '/accounting/journal', label: 'قيود اليومية', icon: ScrollText, roles: ['admin'], condition: 'accountingEnabled', modes: ['enterprise'] },
        { path: '/accounting/general-ledger', label: 'دفتر الأستاذ', icon: FileText, roles: ['admin'], condition: 'accountingEnabled', modes: ['enterprise'] },
        { path: '/accounting/cost-centers', label: 'مراكز التكلفة', icon: Layers, roles: ['admin'], condition: 'accountingEnabled', modes: ['enterprise'] },
        { path: '/accounting/petty-cash', label: 'العهد النقدية', icon: WalletCards, roles: ['admin'], condition: 'accountingEnabled', modes: ['enterprise'] },
        { path: '/accounting/checks', label: 'إدارة الشيكات', icon: Banknote, roles: ['admin'], condition: 'accountingEnabled', modes: ['enterprise'] },
        { path: '/accounting/bank-reconciliation', label: 'مطابقة البنوك', icon: Scale, roles: ['admin'], condition: 'accountingEnabled', modes: ['enterprise'] },
        { path: '/accounting/assets', label: 'الأصول الثابتة', icon: Calculator, roles: ['admin'], condition: 'accountingEnabled', modes: ['enterprise'] },
      ]
    },
    {
      label: 'العمليات المالية المتقدمة',
      section: 'advanced_accounting',
      items: [
        { path: '/accounting/treasury', label: 'الخزينة والسيولة', icon: Landmark, roles: ['admin'], condition: 'accountingEnabled', modes: ['enterprise'] },
        { path: '/accounting/cash-flow', label: 'التدفقات النقدية', icon: Activity, roles: ['admin'], condition: 'accountingEnabled', modes: ['enterprise'] },
        { path: '/accounting/budgeting', label: 'الموازنات', icon: Target, roles: ['admin'], condition: 'accountingEnabled', modes: ['enterprise'] },
        { path: '/accounting/aging', label: 'أعمار الديون', icon: History, roles: ['admin'], condition: 'accountingEnabled', modes: ['enterprise'] },
        { path: '/accounting/cost-accounting', label: 'حسابات التكاليف (Cost)', icon: Calculator, roles: ['admin'], condition: 'accountingEnabled', modes: ['enterprise'] },
        { path: '/accounting/project-accounting', label: 'حسابات المشاريع', icon: Briefcase, roles: ['admin'], condition: 'accountingEnabled', modes: ['enterprise'] },
        { path: '/accounting/partners-equity', label: 'الشركاء والأرباح', icon: Coins, roles: ['admin'], condition: 'accountingEnabled', modes: ['enterprise'] },
        { path: '/accounting/letter-of-credits', label: 'الاعتمادات المستندية', icon: FileSignature, roles: ['admin'], condition: 'accountingEnabled', modes: ['enterprise'] },
        { path: '/accounting/trust-accounts', label: 'حسابات الأمانات', icon: Network, roles: ['admin'], condition: 'accountingEnabled', modes: ['enterprise'] },
        { path: '/accounting/revenue-recognition', label: 'تحقق الإيرادات', icon: FileCheck, roles: ['admin'], condition: 'accountingEnabled', modes: ['enterprise'] },
        { path: '/accounting/deferred-revenues', label: 'إيرادات ومقادمات (تسويات)', icon: ArrowLeftRight, roles: ['admin'], condition: 'accountingEnabled', modes: ['enterprise'] },
        { path: '/accounting/wip-accounting', label: 'حسابات تحت التشغيل', icon: Factory, roles: ['admin'], condition: 'accountingEnabled', modes: ['enterprise'] },
        { path: '/accounting/eosb-accounting', label: 'مخصصات الموظفين', icon: Users, roles: ['admin'], condition: 'accountingEnabled', modes: ['enterprise'] },
      ]
    },
    {
      label: 'الضرائب والإقفال',
      section: 'taxes_closing',
      items: [
        { path: '/accounting/tax', label: 'الضرائب (VAT)', icon: Landmark, roles: ['admin'], condition: 'accountingEnabled', modes: ['enterprise'] },
        { path: '/accounting/zakat-and-taxes', label: 'الزكاة والضرائب المعقدة', icon: Scale, roles: ['admin'], condition: 'accountingEnabled', modes: ['enterprise'] },
        { path: '/accounting/e-invoicing', label: 'الفاتورة الإلكترونية', icon: Receipt, roles: ['admin'], condition: 'accountingEnabled', modes: ['enterprise'] },
        { path: '/accounting/closing', label: 'إقفال السنة', icon: LockKeyhole, roles: ['admin'], condition: 'accountingEnabled', modes: ['enterprise'] },
        { path: '/accounting/audit-trail', label: 'سجل المراجعة والتدقيق', icon: ShieldCheck, roles: ['admin'], condition: 'accountingEnabled', modes: ['enterprise'] },
        { path: '/accounting/reports', label: 'التقارير المالية', icon: BarChart4, roles: ['admin'], condition: 'accountingEnabled', modes: ['enterprise'] },
      ]
    },
    { 
      label: 'الإدارة القانونية',
      section: 'legal', 
      items: [
        { path: '/law-firm', label: 'القضايا والجلسات', icon: Scale, roles: ['admin'], modes: ['enterprise'] },
        { path: '/law-firm/clients-opponents', label: 'الموكلين والخصوم', icon: Users, roles: ['admin'], modes: ['enterprise'] },
        { path: '/law-firm/billing', label: 'المالية والأتعاب', icon: Receipt, roles: ['admin'], modes: ['enterprise'] },
        { path: '/law-firm/agenda', label: 'مفكرة المحامي', icon: CalendarClock, roles: ['admin'], modes: ['enterprise'] },
        { path: '/law-firm/memos-archive', label: 'مكتبة المذكرات', icon: BookOpen, roles: ['admin'], modes: ['enterprise'] },
        { path: '/law-firm/judgments', label: 'الأحكام والتنفيذ', icon: Gavel, roles: ['admin'], modes: ['enterprise'] },
        { path: '/law-firm/investigations', label: 'التحقيقات العمالية', icon: ShieldAlert, roles: ['admin'], modes: ['enterprise'] },
        { path: '/law-firm/power-of-attorney', label: 'الوكالات الشرعية', icon: FileSignature, roles: ['admin'], modes: ['enterprise'] },
        { path: '/law-firm/consultations', label: 'الاستشارات القانونية', icon: MessageSquare, roles: ['admin'], modes: ['enterprise'] },
        { path: '/legal/contracts', label: 'إدارة العقود', icon: FileSignature, roles: ['admin'], modes: ['enterprise'] },
        { path: '/law-firm/ip-trademarks', label: 'الملكية الفكرية', icon: Award, roles: ['admin'], modes: ['enterprise'] },
        { path: '/law-firm/corporate-affairs', label: 'شؤون الشركات', icon: Building, roles: ['admin'], modes: ['enterprise'] },
        { path: '/law-firm/compliance', label: 'الامتثال التشريعي', icon: ShieldCheck, roles: ['admin'], modes: ['enterprise'] },
        { path: '/legal', label: 'أرشيف المستندات', icon: FolderOpen, roles: ['admin'], modes: ['enterprise'] },
        { path: '/legal/employees', label: 'المحامون والموظفون', icon: Users, roles: ['admin'], modes: ['enterprise'] },
        { path: '/legal/attendance', label: 'سجل حضور المحامين', icon: Clock, roles: ['admin'], modes: ['enterprise'] },
      ]
    },
    { 
      label: 'صوالين التجميل والحلاقة',
      section: 'salon', 
      items: [
        { path: '/salon/dashboard', label: 'لوحة قيادة الصالون', icon: LayoutDashboard, roles: ['admin'], modes: ['enterprise', 'service'] },
        { path: '/salon/appointments', label: 'حجوزات المواعيد', icon: CalendarClock, roles: ['admin', 'manager', 'cashier'], modes: ['enterprise', 'service'] },
        { path: '/salon/services', label: 'قائمة الخدمات والباقات', icon: Scissors, roles: ['admin', 'manager'], modes: ['enterprise', 'service'] },
        { path: '/salon/chairs', label: 'إدارة الكراسي والكبائن', icon: LayoutGrid, roles: ['admin', 'manager'], modes: ['enterprise', 'service'] },
        { path: '/salon/staff', label: 'طاقم العمل والخبراء', icon: Users, roles: ['admin', 'manager'], modes: ['enterprise', 'service'] },
        { path: '/salon/commissions', label: 'عمولات الخبراء', icon: Coins, roles: ['admin', 'manager'], modes: ['enterprise', 'service'] },
      ]
    },
    { 
      label: 'التقارير والإحصائيات',
      section: 'reports', 
      items: [
        { path: '/reports', label: 'التقارير', icon: PieChart, roles: ['admin'], modes: ['standard', 'service', 'enterprise'] },
        { path: '/custom-reports', label: 'التقارير المخصصة', icon: FileBarChart, roles: ['admin'], modes: ['enterprise'] },
        { path: '/reports/bi-dashboards', label: 'ذكاء الأعمال (BI)', icon: LineChart, roles: ['admin'], modes: ['enterprise'] },
        { path: '/market-monitor', label: 'مراقبة السوق (AI)', icon: Globe, roles: ['admin'], modes: ['enterprise'] },
      ]
    },
    { 
      label: 'التكوين الإداري',
      section: 'config', 
      items: [
        { path: '/modules', label: 'إدارة التطبيقات (Apps)', icon: LayoutGrid, roles: ['admin'], modes: ['starter', 'standard', 'service', 'enterprise'] },
        { path: '/settings', label: 'الإعدادات', icon: Settings, roles: ['admin'], modes: ['starter', 'standard', 'service', 'enterprise'] },
        { path: '/branches', label: 'إدارة الفروع', icon: Building, roles: ['admin'], modes: ['enterprise'] },
        { path: '/admin/pos-terminals', label: 'أجهزة نقاط البيع', icon: MonitorSmartphone, roles: ['admin'], modes: ['enterprise'] },
        { path: '/approval-workflows', label: 'مسارات الاعتماد', icon: Settings, roles: ['admin'], modes: ['enterprise'] },
        { path: '/admin/system-health', label: 'صحة النظام والأحداث', icon: ShieldCheck, roles: ['admin'], modes: ['enterprise'] },
        { path: '/admin/license-generator', label: 'مولد التراخيص المفاتيح', icon: Key, roles: ['admin'], modes: ['starter', 'standard', 'service', 'enterprise'] },
      ]
    },
    { 
      label: 'أدوات المؤسسة',
      section: 'tools', 
      items: [
        { path: '/dms', label: 'إدارة الوثائق (DMS)', icon: Folder, roles: ['admin'], modes: ['enterprise'] },
        { path: '/legal/signature', label: 'التوقيع الإلكتروني', icon: PenTool, roles: ['admin'], modes: ['enterprise'] },
        { path: '/document-editor', label: 'محرر المستندات', icon: FileEdit, roles: ['admin', 'manager', 'cashier'], modes: ['starter', 'standard', 'service', 'enterprise'] },
        { path: '/internal-communication', label: 'التواصل الداخلي', icon: MessageSquare, roles: ['admin', 'manager'], modes: ['enterprise'] },
        { path: '/website-cms', label: 'إدارة محتوى الموقع', icon: Globe, roles: ['admin'], modes: ['enterprise', 'standard', 'service'] },
        { path: '/hr/analytics', label: 'تحليلات تفاعل الموظفين', icon: Activity, roles: ['admin'], modes: ['enterprise'] },
      ]
    },
    { 
      label: 'إدارة النظام والأمان',
      section: 'system', 
      items: [
        { path: '/owner-cloud', label: 'المركز السحابي للفرع والملاك', icon: Globe, roles: ['admin'], modes: ['starter', 'standard', 'service', 'enterprise'] },
        { path: '/users', label: 'المستخدمين', icon: ShieldCheck, roles: ['admin'], modes: ['enterprise'] },
        { path: '/role-management', label: 'إدارة الصلاحيات', icon: UserCheck, roles: ['admin'], modes: ['enterprise'] },
        { path: '/audit-logs', label: 'سجل التدقيق', icon: ShieldAlert, roles: ['admin'], modes: ['enterprise'] },
        { path: '/admin/server-resources', label: 'موارد السيرفر', icon: Server, roles: ['admin'], modes: ['enterprise'] },
        { path: '/admin/api-keys', label: 'مفاتيح الربط (API Keys)', icon: Key, roles: ['admin'], modes: ['enterprise'] },
        { path: '/admin/user-sessions', label: 'تتبع الجلسات الجغرافية', icon: MapPin, roles: ['admin'], modes: ['enterprise'] },
        { path: '/logbook', label: 'سجل العمليات', icon: Activity, roles: ['admin'], modes: ['enterprise'] }, 
        { path: '/admin/risk-compliance', label: 'المخاطر والامتثال', icon: ShieldAlert, roles: ['admin'], modes: ['enterprise'] },
        { path: '/system-backups', label: 'النسخ الاحتياطي', icon: DatabaseBackup, roles: ['admin'], modes: ['enterprise'] },
        { path: '/recycle-bin', label: 'سلة المهملات', icon: Trash2, roles: ['admin'], modes: ['starter', 'standard', 'service', 'enterprise'] },
        { path: '/notifications', label: 'مركز التنبيهات والإشعارات', icon: Bell, roles: ['admin', 'manager', 'cashier', 'warehouse'], modes: ['starter', 'standard', 'service', 'enterprise'] },
        { path: '/about', label: 'عن النظام', icon: Info, roles: ['admin', 'cashier', 'warehouse'], modes: ['starter', 'standard', 'service', 'enterprise'] },
      ]
    }
];

export const getModeBadge = (currentMode: string) => {
      switch(currentMode) {
          case 'starter': return { label: 'Basic', color: 'bg-emerald-500/20 text-emerald-200 border-emerald-500/30 shadow-[0_0_8px_#34d399]', icon: Zap };
          case 'standard': return { label: 'Standard', color: 'bg-blue-500/20 text-blue-200 border-blue-500/30 shadow-[0_0_8px_#60a5fa]', icon: Store };
          case 'service': return { label: 'Service', color: 'bg-orange-500/20 text-orange-200 border-orange-500/30 shadow-[0_0_8px_#fb923c]', icon: Video };
          case 'enterprise': return { label: 'Enterprise', color: 'bg-purple-500/20 text-purple-200 border-purple-500/30 shadow-[0_0_8px_#a855f7]', icon: Building2 };
          default: return { label: 'Pro', color: 'bg-indigo-500/20 text-indigo-200', icon: Gem };
      }
};

export const normalizeArabic = (text: string) => {
    if (!text) return '';
    return text
      .replace(/[أإآا]/g, 'ا')
      .replace(/ة/g, 'ه')
      .replace(/ي/g, 'ى')
      .toLowerCase();
};
